services:
  # Banco de dados PostgreSQL para autenticação e configurações
  postgres:
    image: postgres:15-alpine
    container_name: guacamole-postgres
    restart: unless-stopped
    env_file:
      - config.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-guacamole_db}
      POSTGRES_USER: ${POSTGRES_USER:-guacamole_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guacamole_secure_password_123}
      PGDATA: ${POSTGRES_DATA_PATH:-/var/lib/postgresql/data}/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - guacamole-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-guacamole_user} -d ${POSTGRES_DB:-guacamole_db}"]
      interval: ${HEALTH_CHECK_INTERVAL:-30}s
      timeout: ${HEALTH_CHECK_TIMEOUT:-10}s
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-30}s

  # Daemon guacd para protocolos de conexão remota 
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacamole-guacd
    restart: unless-stopped
    env_file:
      - config.env
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
    networks:
      - guacamole-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${GUACD_PORT:-4822}"]
      interval: ${HEALTH_CHECK_INTERVAL:-30}s
      timeout: ${HEALTH_CHECK_TIMEOUT:-10}s
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-30}s

  # Aplicação web Guacamole
  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole-web
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      guacd:
        condition: service_healthy
    environment:
      # Configuração do guacd
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      
      # Configuração PostgreSQL (usando POSTGRESQL_* para evitar conflitos)
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: guacamole_user
      POSTGRESQL_PASSWORD: guacamole_secure_password_123
      
      # Desabilitar leitura de outras variáveis de ambiente
      ENABLE_ENVIRONMENT_PROPERTIES: false
      PROXY_IP_HEADER: ${PROXY_IP_HEADER:-X-Forwarded-For}
      PROXY_PROTOCOL_HEADER: ${PROXY_PROTOCOL_HEADER:-X-Forwarded-Proto}
      
    ports:
      - "${GUACAMOLE_PORT:-80}:8080"
    networks:
      - guacamole-network
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/guacamole/"]
      interval: ${HEALTH_CHECK_INTERVAL:-30}s
      timeout: ${HEALTH_CHECK_TIMEOUT:-10}s
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: 60s

volumes:
  postgres_data:
    driver: local

networks:
  guacamole-network:
    driver: bridge
    name: guacamole-network
